### ISSUE TITLE
Use of Widgets for Side Bar Not Documented

### ISSUE THREAD

**Issue by gordonbanderson** [silverstripe/silverstripe-blog#226]
Whilst I am happy to provide a pull request I just wish to double check this is the correct way to enable the widgets (using a YML file), it appears to work for me.

```yml
Blog:
  extensions:
    - WidgetPageExtension
BlogPost:
  extensions:
    - WidgetPageExtension
```
